### PR TITLE
Add pt-rBR strings

### PR DESCRIPTION
**Pull request by rffontenelle**
Brazilian Portuguese translation

### CODE REVIEW

**Comment by rffontenelle** [comment]
Why another Pull Request?

**Comment by Lesik** [comment]
@rffontenelle You have to answer that question, it was you who opened it

**Comment by rffontenelle** [comment]
I see. I really don't know how this happened. Anyway, thanks for merging.

**Comment by Lesik** [comment]
Thanks for contributing!

**Pull request merged**
